# Generated by Django 5.2.4 on 2025-07-07 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdomainpermission',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain'),
        ),
        migrations.AddField(
            model_name='userdomainpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdomainpermission',
            unique_together={('user', 'domain')},
        ),
    ]
