# Generated by Django 5.2.4 on 2025-07-14 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('domains', '0005_dnsrecord_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdomainpermission',
            name='allowed_a_record',
            field=models.ForeignKey(blank=True, help_text='Registro A/AAAA que o usuário pode visualizar neste domínio.', limit_choices_to={'record_type__in': ['A', 'AAAA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_for_permissions', to='domains.dnsrecord'),
        ),
    ]
