# Generated by Django 5.2.4 on 2025-07-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdomainpermission_allowed_a_record'),
        ('domains', '0005_dnsrecord_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdomainpermission',
            unique_together={('user', 'domain', 'allowed_a_record')},
        ),
    ]
