# Generated by Django 5.2.4 on 2025-07-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(default='active', max_length=32),
        ),
    ]
