# Generated by Django 5.2.4 on 2025-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='cloudflare_zone_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
