# Generated by Django 5.2.4 on 2025-07-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_alter_domain_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
